# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
  . /etc/bashrc
fi

# Git enabled prompt
if [ -f ~/.bin/git_prompt ]; then
  . ~/.bin/git_prompt
  export GIT_PS1_SHOWDIRTYSTATE=1
  export PS1='\u@\h:\w$(__git_ps1 " (%s)")\$ '
else
  export PS1='\u@\h:\w\$ '
fi

# Path (notice the change for macOS)
if [ $(uname) = Darwin ]; then
    PYBINPATH=$HOME/Library/Python/3.8/bin
    PATH="/Library/Frameworks/Python.framework/Versions/3.8/bin:${PATH}"
else
    PYBINPATH=$HOME/.local/bin
fi

export PATH=$HOME/.bin:$PYBINPATH:$PATH

# GDL path
export GDL_STARTUP=~/.gdl/gdlrc

# Locale stuff
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
