set nobackup
set number
syntax on
set colorcolumn=80
set expandtab
set shiftwidth=4
set autoindent
set smartindent
set cindent

filetype plugin indent on

"set mouse=a

set laststatus=2
set noswapfile
set hlsearch
set ruler
