#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

PATH="/home/${USER}/.bin":$PATH
PS1='\[\e[0;37m\]\u\[\e[37m\]@\[\e[0;37m\]\h\[\e[0m\] \[\e[0;37m\]\w: \[\e[0m\]'

alias grep='grep --color -n'
alias ls='ls --color=auto'
alias ll='ls -l'
alias xup='xrdb ~/.Xresources'
