# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
  . /etc/bashrc
fi

# Git enabled prompt
if [ -f ~/.bin/git-sh-prompt ]; then
  . ~/.bin/git-sh-prompt
  export GIT_PS1_SHOWDIRTYSTATE=1
  export PS1='\u@\h:\w$(__git_ps1 " (%s)")\$ '
else
  export PS1='\u@\h:\w\$ '
fi

# Path
export PATH=/home/bandang0/.bin:/home/bandang0/.local/bin:$PATH
